server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: Senha@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
    serialization:
     fail-on-empty-beans: false
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
    password: Senha@123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka