application:
  yml:
spring:
  application:
    name: greeting-services
management:
  endpoint:
    web:
      exposure:
        include:
          - '*'
greeting-services:
  greeting: "Cia"
  default-value: "Mondo"